name: Look WEB - CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - develop
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Compose Docker tag
        id: compose_docker_tag
        run: echo "##[set-output name=tag;]$(echo ${{ secrets.DOCKER_WEB_REPOSITORY }}:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }})"

      - name: Build Docker image
        working-directory: frontend
        run: |
          docker build --file deployment/docker/Dockerfile -t ${{ steps.compose_docker_tag.outputs.tag }} .

      - name: Push Docker image
        working-directory: frontend
        run: |
          docker push ${{ steps.compose_docker_tag.outputs.tag }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        if: ${{ steps.extract_branch.outputs.branch == 'develop' || steps.extract_branch.outputs.branch == 'main' }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deployment process..."